### ISSUE TITLE
Clicking on a search result won't open the project

### ISSUE THREAD

**Issue by axelgenus** [lunaryorn/gnome-search-providers-jetbrains#16] opened 2021-05-19 17:24 UTC
I have noticed this issue on Rider, WebStorm and also PhpStorm. Basically, after clicking on a search result, the IDE is going to open correctly but the selected project won't. According to the default IDE behavior it is going to open the last opened project or the project/solution selection dialog.

I'm looking into it but could not find a solution yet. It seems like the IDE is started without the project path as parameter.

**Comment by lunaryorn** [comment] 2021-05-19 19:46
I'll need the log if I'm to do anything about it 🤷‍♂️

**Comment by lunaryorn** [comment] 2021-05-20 06:20
@axelgenus I am sorry but I cannot reproduce this behaviour with the latest release.  I'm closing this issue because I can't currently act on it; please do reopen if you can provide more information for me to debug the problem, and do feel free to make a pull request if you find something that needs fixing.

**Closed by lunaryorn** 2021-05-20 06:20 UTC

**Comment by axelgenus** [comment] 2021-05-20 06:25
Here is the log.

[gnome-search-providers-jetbrains.log](https://github.com/lunaryorn/gnome-search-providers-jetbrains/files/6513392/gnome-search-providers-jetbrains.log)

**Comment by lunaryorn** [comment] 2021-05-20 08:08
Update to the latest version and check again.  Other than that I don't see anything in the logs.

If it doesn't work on the latest version then I'm afraid you're on your own.
